{
  "admin": ["administration"],
  "analytics": ["metrics"],
  "assets": [],
  "authentication": ["login", "signup"], 
  "authorization": ["permissions", "roles"], 
  "blockchain": [],
  "caching": ["redis", "memcache"],
  "captcha": [],
  "cms": [],
  "cookie": [],
  "concurrency": [],
  "configuration": [],
  "crawlers": ["scrapers"],
  "cryto": [],
  "database": ["postgres", "mysql", "sqlite", "graphql"],
  "debugging": ["debugger"],
  "decorators": [],
  "devops": ["deployments"],
  "diff": [],
  "documentation": [],
  "email": ["newsletters"],
  "encryption": [],
  "error": ["error handling", "error reporting"],
  "form": ["forms"],
  "game development": ["video games", "gaming"],
  "generators": ["scaffold"],
  "geolocation": ["geocode"],
  "interfaces": ["user interface", "gui"],
  "html parsing": [],
  "image processing": ["image resizing"],
  "internationalization": ["i18n"],
  "javascript": ["js"], 
  "json": [],
  "logging": ["logger"],
  "machine learning": ["natural language"],
  "measurements": [],
  "messaging": ['xmpp'],
  "networking": [],
  "optimization": [],
  "orm": ["object relational mapping"],
  "pagination": ["paging", "infinite scroll"],
  "payments": ["stripe", "credit cards"],
  "pdf": [],
  "performance": [],
  "barcodes": ["qr", "barcode", "barcodes", "code 11", "code 25", "code 39", "code 49", "code 93", "code 128", "ean 2", "ean 5", "ean 8", "ean 13", "itf 6", "itf 14"],
  "queues": [],
  "realtime": [],
  "rss": [], 
  "scheduling": [],
  "search": [], 
  "security": [],
  "seo": ["search engine optimization"],
  "sitemap": [],
  "spam": [],
  "storage": ["s3"],
  "styling": [],
  "templates": ["slim", "haml", "erb"],
  "testing": ["tdd", "tests"],
  "upload": [],
  "video": [""],
  "visualization": [],
  "websocket": [],
  "xml parsing": []
}.each do |name, synonyms|
  tag = Tag.create(name: name, synonyms: synonyms.unshift(name))
  puts tag.inspect
end